import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body className="px-4">
          <ClerkLoading>
            <div className="flex items-center justify-center animate-spin h-24 w-24 rounded-full border border-red-700"></div>
          </ClerkLoading>
          <ClerkLoaded>
            <Header />
            <div className="">{children}</div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
